export const symbols = {
        parenthesisOpen: '(',
        parenthesisClose: ')',
        curlyBracketsOpen: '{',
        curlyBracketsClose: '}',
        squareBracketsOpen: '[',
        squareBracketsClose: ']',
        angleBracketsClose: ">",
        angleBracketsOpen: "<",
        singleQuote: "'",
        doubleQuotes: '"',
        backTick: '`',
        dot: ".",
        exclamation: "!",
        question: "?",
        comma: ",",
        hyphen: "-",
        underscore: "_",
        backslash: "\\",
        slash: "/",
        at: "@",
        hash: "#",
        asterisk: "*",
        plus: "+",
        minus: "-",
        colon: ":",
        semicolon: ";",
        bar: "|",
        and: "&",
        xor: "^",
        percent: "%",
        dollar: "$",
        
}